# Dispara automaticamente ao fazer push na main
on:
  push:
    branches: [main]

name: Deploy

jobs:
  deploy:
    # Roda em um runner Ubuntu do GitHub
    runs-on: ubuntu-latest

    steps:
      # Conecta no servidor via SSH com usuário e senha
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          # IP do servidor
          host: ${{ secrets.SSH_HOST }}
          # Usuário (root)
          username: ${{ secrets.SSH_USER }}
          # Senha do servidor
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            # Entra na pasta do projeto
            cd /home/nocautboxe/htdocs/nocautboxe.com

            git pull origin main
            chown -R nocautboxe:nocautboxe /home/nocautboxe/htdocs/nocautboxe.com